### ISSUE TITLE
Dependency issue 

### ISSUE THREAD

**Issue by shenvitor** [ComPWA/compwa.github.io#272]
### What happened?
[TR-000](https://compwa.github.io/report/000.html) run in Colab is not successful due to the following issues.

### Relevant log output

![Screenshot 2024-05-06 at 15 33 09](https://github.com/ComPWA/compwa.github.io/assets/17490173/7e6037ca-c2d9-417b-879f-3724a5daa593)

### Is it possible to reproduce the bug with a small code snippet?

See above

### Additional steps to reproduce the bug

No

### Which Python version were you using?

None

**Comment by redeboer** [comment]
Thanks for posting! Resolving the conflict for this notebook should be easy, but it does point to a larger problem with the dependency 'pinning' in the technical reports (see also https://github.com/ComPWA/compwa.github.io/pull/256, and indirectly the discussion in https://github.com/ComPWA/compwa.github.io/pull/151#issuecomment-1235586816). The ideal would be to pin all dependencies instead of only the direct ones.

@shenvitor can you fix the notebook for this bug by finding a `jaxlib` version that works and pinning to that? A solution should be found for the larger issue here, but I'll describe that in a different issue.

**Comment by shenvitor** [comment]
[Dependency Resolution]
(https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts)
